const $=s=>document.querySelector(s),today=new Date(),dayKey=today.toLocaleDateString("sv-SE"),STORE="n1-daily-progress-v1",GENERATED="n1-generated-sets-v1";
const h=value=>String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const read=(key,fallback={})=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
const save=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const load=()=>read(STORE),completed=()=>Object.values(load()).filter(r=>r.total===23);
let sets=[...window.DAILY_SETS,...read(GENERATED,[])],set=sets.find(s=>!completed().some(r=>r.set===s.id)),all=set?[...set.grammar,...set.reading.questions,...set.listening.questions]:[];
let orders={},submitted=false,playbackStopped=false,generating=false;
const choice=(q,prefix)=>`<div class="question" data-id="${h(q.id)}"><p class="question-title"><span class="tag">${h(q.skill)}</span>${h(q.text)}</p><div class="options">${q.options.map((o,i)=>`<label class="option"><input type="radio" name="${prefix}-${h(q.id)}" value="${i}"><span>${i+1}. ${h(o)}</span></label>`).join("")}</div><div class="feedback"></div></div>`;
const order=q=>`<div class="question" data-id="${h(q.id)}"><p class="question-title"><span class="tag">${h(q.skill)}</span>${h(q.text)}</p><div class="order-answer" data-order-answer="${h(q.id)}"><span class="order-hint">按正确顺序点击下方词块</span></div><div class="order-bank">${q.words.map((w,i)=>`<button class="word-chip" type="button" data-order="${h(q.id)}" data-index="${i}">${h(w)}</button>`).join("")}</div><button class="ghost clear-order" type="button" data-clear="${h(q.id)}">重排</button><div class="feedback"></div></div>`;
function selectSet(next){set=next;all=[...set.grammar,...set.reading.questions,...set.listening.questions];orders={};submitted=false;render();scrollTo({top:0,behavior:"smooth"})}
function render(){
  $("#todayLabel").textContent=today.toLocaleDateString("zh-CN",{year:"numeric",month:"long",day:"numeric",weekday:"long"});
  $("#resultPanel").hidden=true;$("#practiceForm").hidden=!set;
  if(!set){showGeneratePanel("已完成所有已发布套题，正在准备新的原创练习……",true);generateNext();return}
  $("#setIntro").textContent=`${set.title} · ${set.intro}`;$("#submitButton").textContent="提交本套练习";$("#submitButton").disabled=false;
  $("#grammarQuestions").innerHTML=set.grammar.map(q=>q.type==="order"?order(q):choice(q,"g")).join("");
  $("#readingPassage").innerHTML=`<h3>${h(set.reading.title)}</h3><div>${h(set.reading.passage)}</div>`;
  $("#readingQuestions").innerHTML=set.reading.questions.map(q=>choice(q,"r")).join("");
  $("#listeningQuestions").innerHTML=set.listening.questions.map(q=>choice(q,"l")).join("");
  $("#transcript").hidden=true;$("#transcript p").textContent=set.listening.script;$("#audioStatus").textContent="播放期间不会显示原文与答案";
  document.querySelectorAll("[data-order]").forEach(b=>b.onclick=()=>pickWord(b));document.querySelectorAll("[data-clear]").forEach(b=>b.onclick=()=>clearOrder(b.dataset.clear));document.querySelectorAll("input").forEach(i=>i.onchange=updateProgress);updateProgress();
}
function pickWord(b){if(submitted)return;const id=b.dataset.order;orders[id]??=[];orders[id].push(+b.dataset.index);b.disabled=true;paintOrder(id);updateProgress()}
function clearOrder(id){if(submitted)return;orders[id]=[];document.querySelectorAll(`[data-order="${id}"]`).forEach(b=>b.disabled=false);paintOrder(id);updateProgress()}
function paintOrder(id){const box=document.querySelector(`[data-order-answer="${id}"]`),q=set.grammar.find(x=>x.id===id),picked=orders[id]||[];box.innerHTML=picked.length?picked.map(i=>`<span class="word-chip">${h(q.words[i])}</span>`).join(""):'<span class="order-hint">按正确顺序点击下方词块</span>'}
function answerFor(q){if(q.type==="order")return orders[q.id]||[];const el=document.querySelector(`[data-id="${q.id}"] input:checked`);return el?+el.value:null}
function isAnswered(q){const a=answerFor(q);return Array.isArray(a)?a.length===q.words.length:a!==null}
function isCorrect(q){const a=answerFor(q);return Array.isArray(q.answer)?q.answer.join()===a.join():q.answer===a}
function updateProgress(){const done=all.filter(isAnswered).length,p=Math.round(done/all.length*100);$("#progressPercent").textContent=p+"%";$("#answerStatus").textContent=`已完成 ${done}/${all.length} 题。提交前不会显示答案。`}
function speak(){if(!("speechSynthesis" in window))return $("#audioStatus").textContent="此浏览器不支持语音播放，请换用 Edge、Chrome 或 Safari。";playbackStopped=false;speechSynthesis.cancel();const parts=set.listening.script.split(/\n\n+/),voices=speechSynthesis.getVoices().filter(v=>v.lang.startsWith("ja"));$("#audioStatus").textContent="正在连续播放整组听力…";const next=i=>{if(playbackStopped)return;if(i===parts.length){$("#audioStatus").textContent="播放完毕，请统一作答。";return}const u=new SpeechSynthesisUtterance(parts[i]);u.lang="ja-JP";u.rate=.88;if(voices.length)u.voice=voices[i%voices.length];u.onend=()=>next(i+1);u.onerror=()=>{if(!playbackStopped)$("#audioStatus").textContent="播放未完成，请重试或检查浏览器语音设置。"};speechSynthesis.speak(u)};next(0)}
function submit(e){e.preventDefault();if(submitted)return;const missing=all.filter(q=>!isAnswered(q));if(missing.length){$("#answerStatus").textContent=`还有 ${missing.length} 题未完成，请答完后统一提交。`;document.querySelector(`[data-id="${missing[0].id}"]`).scrollIntoView({behavior:"smooth",block:"center"});return}
  submitted=true;playbackStopped=true;window.speechSynthesis?.cancel();let correct=0,wrong=[];all.forEach(q=>{const ok=isCorrect(q);correct+=ok?1:0;if(!ok)wrong.push(q);const el=document.querySelector(`[data-id="${q.id}"]`);el.classList.add(ok?"correct":"wrong");el.querySelector(".feedback").innerHTML=`<p class="explanation"><strong>${ok?"正确":"答错了"}。</strong> ${h(q.explanation)}</p>`});
  document.querySelectorAll("input,button.word-chip,button.clear-order").forEach(x=>x.disabled=true);$("#transcript").hidden=false;const pct=Math.round(correct/all.length*100),history=load();history[`${set.id}-${Date.now()}`]={date:dayKey,set:set.id,title:set.title,correct,total:all.length,wrong:wrong.map(q=>({id:q.id,skill:q.skill,text:q.text}))};save(STORE,history);
  const next=sets.find(s=>!completed().some(r=>r.set===s.id));$("#resultPanel").innerHTML=`<h2>本套练习完成</h2><div class="result-grid"><div class="result-stat"><span>正确率</span><strong>${pct}%</strong></div><div class="result-stat"><span>答对</span><strong>${correct}/${all.length}</strong></div><div class="result-stat"><span>需复习</span><strong>${wrong.length} 题</strong></div></div>${wrong.length?`<div class="review"><h3>本套错题与薄弱点</h3><ul>${wrong.map(q=>`<li><strong>${h(q.skill)}</strong>：${h(q.text)}</li>`).join("")}</ul></div>`:'<p>全对。保持这个节奏！</p>'}<p id="nextStatus">${next?"下一套已准备好。":"正在生成下一套原创练习，请稍候……"}</p><button id="nextSetButton" class="primary" type="button" ${next?"":"disabled"}>立即进入下一套原创练习</button>`;
  $("#resultPanel").hidden=false;$("#submitButton").textContent="本套已完成";$("#submitButton").disabled=true;$("#progressPercent").textContent="100%";$("#resultPanel").scrollIntoView({behavior:"smooth"});if(next)$("#nextSetButton").onclick=()=>selectSet(next);else generateNext(true);
}
function showGeneratePanel(message,auto=false){$("#setIntro").textContent="旧题不会循环";$("#progressPercent").textContent="100%";$("#resultPanel").hidden=false;$("#resultPanel").innerHTML=`<h2>本轮题库已完成</h2><p id="nextStatus">${h(message)}</p><button id="nextSetButton" class="primary" type="button" ${auto?"disabled":""}>${auto?"正在生成…":"生成下一套原创练习"}</button>`;if(!auto)$("#nextSetButton").onclick=()=>generateNext()}
async function generateNext(fromResult=false){
  if(generating)return;generating=true;const status=$("#nextStatus"),button=$("#nextSetButton");if(status)status.textContent="AI 正在生成文法、阅读和听力，共 23 题…";if(button){button.disabled=true;button.textContent="正在生成…"}
  try{const recent=sets.slice(-3),avoid=recent.flatMap(s=>[s.title,...s.grammar.map(q=>q.text),...s.reading.questions.map(q=>q.text),...s.listening.questions.map(q=>q.text)]);let code=sessionStorage.getItem("n1-practice-code")||"";let response=await requestSet(avoid,code);if(response.status===401){code=prompt("请输入你在 Vercel 中设置的 PRACTICE_ACCESS_CODE")||"";if(!code)throw new Error("未输入访问码");sessionStorage.setItem("n1-practice-code",code);response=await requestSet(avoid,code)}const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`生成失败（${response.status}）`);const generated=read(GENERATED,[]);generated.push(body.set);save(GENERATED,generated);sets.push(body.set);if(fromResult){status.textContent="新题已生成，不会重复旧套题。";button.disabled=false;button.textContent="立即进入下一套原创练习";button.onclick=()=>selectSet(body.set)}else selectSet(body.set)}catch(error){const message=`${error.message}。请检查 Vercel 环境变量后重试。`;if(fromResult){status.textContent=message;button.disabled=false;button.textContent="重试生成";button.onclick=()=>generateNext(true)}else showGeneratePanel(message)}finally{generating=false}
}
const requestSet=(avoid,code)=>fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json",...(code?{"x-practice-code":code}:{})},body:JSON.stringify({avoid})});
function showStats(){const rows=completed().sort((a,b)=>b.date.localeCompare(a.date)),counts={};rows.flatMap(r=>r.wrong).forEach(w=>counts[w.skill]=(counts[w.skill]||0)+1);const avg=rows.length?Math.round(rows.reduce((s,r)=>s+r.correct/r.total,0)/rows.length*100):0;$("#statsContent").innerHTML=`<div class="result-grid"><div class="result-stat"><span>完成套数</span><strong>${rows.length}</strong></div><div class="result-stat"><span>平均正确率</span><strong>${avg}%</strong></div><div class="result-stat"><span>累计错题</span><strong>${rows.reduce((s,r)=>s+r.wrong.length,0)}</strong></div></div><h3>薄弱点</h3>${Object.keys(counts).length?`<ul class="weak-list">${Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<li>${h(k)} × ${v}</li>`).join("")}</ul>`:"<p>完成练习后，这里会自动汇总。</p>"}<h3>完成记录</h3><div class="history-list">${rows.length?rows.map(r=>`<div class="history-row"><strong>${h(r.date)}</strong><span>${r.correct}/${r.total}</span><span>正确率 ${Math.round(r.correct/r.total*100)}%</span></div>`).join(""):"<p>暂无记录</p>"}</div>`;$("#statsDialog").showModal()}
$("#playAudio").onclick=speak;$("#stopAudio").onclick=()=>{playbackStopped=true;window.speechSynthesis?.cancel();$("#audioStatus").textContent="已停止，可从头重新播放。"};$("#practiceForm").onsubmit=submit;$("#statsButton").onclick=showStats;$("#closeStats").onclick=()=>$("#statsDialog").close();render();

